export interface EmojiItem {
  char: string;
  name: string;
}

/**
 * 内置常用 emoji（含名称以支持搜索）；如现有数据用到 </> 这类符号，
 * 选择器提供「自定义」输入框兜底。外置自 EmojiPicker.vue 以降低组件体积。
 */
export const EMOJIS: EmojiItem[] = [
  { char: '⭐', name: 'star star' },
  { char: '☆', name: 'star outline' },
  { char: '🔥', name: 'fire hot' },
  { char: '💡', name: 'idea light bulb' },
  { char: '⚙️', name: 'gear settings config' },
  { char: '</>', name: 'code tag' },
  { char: '📘', name: 'book blue doc' },
  { char: '📗', name: 'book green doc' },
  { char: '📙', name: 'book orange doc' },
  { char: '📚', name: 'books library' },
  { char: '📖', name: 'book open read' },
  { char: '📝', name: 'memo note write' },
  { char: '📌', name: 'pin push' },
  { char: '📎', name: 'paperclip attach' },
  { char: '✂️', name: 'scissors cut' },
  { char: '🔖', name: 'bookmark tag' },
  { char: '🏷️', name: 'label tag price' },
  { char: '🗂️', name: 'folder tabs' },
  { char: '📁', name: 'folder open' },
  { char: '📂', name: 'folder closed' },
  { char: '🗃️', name: 'card file box' },
  { char: '💼', name: 'briefcase work' },
  { char: '🧩', name: 'puzzle game' },
  { char: '🎮', name: 'game controller' },
  { char: '🕹️', name: 'joystick' },
  { char: '🎯', name: 'target dart' },
  { char: '🎲', name: 'dice' },
  { char: '🎨', name: 'art palette paint' },
  { char: '🖌️', name: 'paintbrush design' },
  { char: '🎬', name: 'movie clapper film' },
  { char: '🎭', name: 'theater masks drama' },
  { char: '🎵', name: 'music note' },
  { char: '🎶', name: 'music notes' },
  { char: '🎧', name: 'headphones listen' },
  { char: '🎤', name: 'microphone sing' },
  { char: '📺', name: 'tv television' },
  { char: '📷', name: 'camera photo' },
  { char: '🖥️', name: 'desktop computer' },
  { char: '💻', name: 'laptop computer' },
  { char: '⌨️', name: 'keyboard' },
  { char: '🖱️', name: 'mouse' },
  { char: '📱', name: 'phone mobile' },
  { char: '📡', name: 'satellite signal' },
  { char: '🔋', name: 'battery' },
  { char: '🔌', name: 'plug power' },
  { char: '🌐', name: 'globe web internet' },
  { char: '🔗', name: 'link chain' },
  { char: '🛰️', name: 'satellite' },
  { char: '🤖', name: 'robot ai' },
  { char: '🧠', name: 'brain ai think' },
  { char: '👾', name: 'alien monster' },
  { char: '⚡', name: 'lightning bolt fast' },
  { char: '🚀', name: 'rocket launch deploy' },
  { char: '🏗️', name: 'build scaffold construction' },
  { char: '🔧', name: 'wrench tool fix' },
  { char: '🔨', name: 'hammer tool' },
  { char: '🛠️', name: 'tools hammer wrench' },
  { char: '🧰', name: 'toolbox' },
  { char: '☕', name: 'coffee java drink tea' },
  { char: '🐍', name: 'snake python' },
  { char: '🌱', name: 'seedling spring plant' },
  { char: '🌟', name: 'glowing star' },
  { char: '💎', name: 'gem diamond' },
  { char: '🧪', name: 'test tube science' },
  { char: '🔬', name: 'microscope science' },
  { char: '🩺', name: 'stethoscope health' },
  { char: '📊', name: 'chart bar data' },
  { char: '📈', name: 'chart up growth' },
  { char: '📉', name: 'chart down' },
  { char: '🧮', name: 'abacus calc' },
  { char: '🔢', name: 'numbers' },
  { char: '🧬', name: 'dna biology' },
  { char: '🎓', name: 'graduation school' },
  { char: '✏️', name: 'pencil write' },
  { char: '🖊️', name: 'pen write' },
  { char: '🔍', name: 'search magnifier' },
  { char: '🔎', name: 'search zoom' },
  { char: '🗺️', name: 'map travel' },
  { char: '🌍', name: 'earth globe' },
  { char: '✈️', name: 'plane travel' },
  { char: '🚗', name: 'car drive' },
  { char: '🏠', name: 'home house' },
  { char: '🏢', name: 'office building' },
  { char: '🏪', name: 'convenience store' },
  { char: '🛒', name: 'cart shopping' },
  { char: '💰', name: 'money bag' },
  { char: '💳', name: 'card credit' },
  { char: '📦', name: 'package box' },
  { char: '🚚', name: 'truck delivery' },
  { char: '⚖️', name: 'balance law scale' },
  { char: '🏆', name: 'trophy win' },
  { char: '🥇', name: 'medal gold' },
  { char: '❤️', name: 'heart love' },
  { char: '💬', name: 'speech bubble chat comment' },
  { char: '👥', name: 'people group users' },
  { char: '👤', name: 'user person' },
  { char: '🔔', name: 'bell notification' },
  { char: '⏰', name: 'clock alarm time' },
  { char: '📅', name: 'calendar date' },
  { char: '🗓️', name: 'calendar spiral' },
  { char: '📰', name: 'news newspaper' },
  { char: '📻', name: 'radio' },
  { char: '🍔', name: 'burger food' },
  { char: '🍵', name: 'tea drink' },
  { char: '🎁', name: 'gift present' },
  { char: '✅', name: 'check done' },
  { char: '❌', name: 'cross no error' },
  { char: '⚠️', name: 'warning caution' },
  { char: '❓', name: 'question help' },
  { char: '🔒', name: 'lock secure' },
  { char: '🔑', name: 'key' },
  { char: '🌈', name: 'rainbow' },
  { char: '☀️', name: 'sun weather' },
  { char: '🌙', name: 'moon night' },
  { char: '⭕', name: 'circle' },
  { char: '🔵', name: 'blue circle' },
  { char: '🟢', name: 'green circle' },
  { char: '🟡', name: 'yellow circle' },
  { char: '🔴', name: 'red circle' },
  { char: '⚪', name: 'white circle' },
  { char: '🆗', name: 'ok' },
  { char: '🆕', name: 'new' },
  { char: '🅰️', name: 'a' },
  { char: '🅱️', name: 'b' },
  { char: '🌀', name: 'cyclone swirl' },
];
