/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLinks: typeof import('./components/admin/AdminLinks.vue')['default']
    CategoryIcon: typeof import('./components/ui/CategoryIcon.vue')['default']
    CategoryTree: typeof import('./components/admin/CategoryTree.vue')['default']
    DevAdminEntry: typeof import('./components/admin/DevAdminEntry.vue')['default']
    EmojiPicker: typeof import('./components/ui/EmojiPicker.vue')['default']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    MainHeader: typeof import('./components/layout/MainHeader.vue')['default']
    Pagination: typeof import('./components/ui/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./components/ui/ScrollToTop.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SiteCard: typeof import('./components/ui/SiteCard.vue')['default']
    SubCategoryTabs: typeof import('./components/ui/SubCategoryTabs.vue')['default']
    TimeDateComponent: typeof import('./components/ui/TimeDateComponent.vue')['default']
    ToastHost: typeof import('./components/ui/ToastHost.vue')['default']
  }
}
