/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    MainHeader: typeof import('./components/layout/MainHeader.vue')['default']
    MiniPlayer: typeof import('./components/MusicPlayer/MiniPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./components/ui/ScrollToTop.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SiteCard: typeof import('./components/ui/SiteCard.vue')['default']
    SubCategoryTabs: typeof import('./components/ui/SubCategoryTabs.vue')['default']
    TimeDateComponent: typeof import('./components/ui/TimeDateComponent.vue')['default']
  }
}
