/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminBadge: typeof import('./components/admin/ui/AdminBadge.vue')['default']
    AdminBarChart: typeof import('./components/admin/ui/AdminBarChart.vue')['default']
    AdminCard: typeof import('./components/admin/ui/AdminCard.vue')['default']
    AdminCategories: typeof import('./components/admin/AdminCategories.vue')['default']
    AdminDashboard: typeof import('./components/admin/AdminDashboard.vue')['default']
    AdminDrawer: typeof import('./components/admin/ui/AdminDrawer.vue')['default']
    AdminEmpty: typeof import('./components/admin/ui/AdminEmpty.vue')['default']
    AdminLinksTable: typeof import('./components/admin/AdminLinksTable.vue')['default']
    AdminModal: typeof import('./components/admin/ui/AdminModal.vue')['default']
    AdminPagination: typeof import('./components/admin/ui/AdminPagination.vue')['default']
    AdminSearch: typeof import('./components/admin/AdminSearch.vue')['default']
    AdminSettings: typeof import('./components/admin/AdminSettings.vue')['default']
    AdminSidebar: typeof import('./components/admin/AdminSidebar.vue')['default']
    AdminSkeleton: typeof import('./components/admin/ui/AdminSkeleton.vue')['default']
    AdminStatCard: typeof import('./components/admin/ui/AdminStatCard.vue')['default']
    AdminSwitch: typeof import('./components/admin/ui/AdminSwitch.vue')['default']
    AdminTopbar: typeof import('./components/admin/AdminTopbar.vue')['default']
    CategoryIcon: typeof import('./components/ui/CategoryIcon.vue')['default']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    IntegrityCheck: typeof import('./components/admin/IntegrityCheck.vue')['default']
    MainHeader: typeof import('./components/layout/MainHeader.vue')['default']
    Pagination: typeof import('./components/ui/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SiteCard: typeof import('./components/ui/SiteCard.vue')['default']
    SubCategoryMenu: typeof import('./components/ui/SubCategoryMenu.vue')['default']
    TimeDateComponent: typeof import('./components/ui/TimeDateComponent.vue')['default']
    ToastHost: typeof import('./components/ui/ToastHost.vue')['default']
    UserPrefsPanel: typeof import('./components/ui/UserPrefsPanel.vue')['default']
  }
}
